stages:
  - setup-database
  - unit-test

variables:
  MYSQL_DATABASE: "GestionUserVersMicro"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: "toor"
  MYSQL_PASSWORD: ""
  MYSQL_HOST: mysql
 
  IMAGE_MAVEN: maven:3.8.3

setup-database:
  stage: setup-database
  services:
    - name: mysql:8.0
      alias: mysql
unit-test:
  image: $IMAGE_MAVEN
  stage: unit-test
  services:
    - name: mysql:8.0
      alias: mysql
  script:
    - echo "Running unit tests..."
    # Assuming your tests use Maven to run and require the MySQL database
    - mvn test -Dspring.datasource.url=jdbc:mysql://mysql:3306/$MYSQL_DATABASE -Dspring.datasource.username=$MYSQL_USER -Dspring.datasource.password=$MYSQL_PASSWORD
