stages:
  - clean
  - build
  - static-code-analysis
  - unit-test
  - coverage-test
  - release
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_MAVEN: maven:3.8.3

clean:
  image: $IMAGE_MAVEN
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - mvn clean

build:
  image: $IMAGE_MAVEN
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn install -B -DskipTests
  artifacts:
    paths:
      - target/  # Adjust the artifact path as per Maven's build output

static-code-analysis:
  image: $IMAGE_MAVEN
  stage: static-code-analysis
  script:
    - echo "Running Static Code Analysis..."
    - echo "Checking duplicated code..."
    - mvn pmd:cpd-check
    - echo "Checking code standard..."
    - mvn pmd:pmd

unit-test:
  image: $IMAGE_MAVEN
  stage: unit-test
  script:
    - echo "Running unit tests..."
    - mvn test 

coverage-test:
  image: $IMAGE_MAVEN
  services:
    - mysql:8
  stage: coverage-test
  needs:
    - job: unit-test
  script:
    - echo "Running coverage tests..."
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest  # Adjust the image as needed
  rules:
    - if: $CI_COMMIT_BRANCH == "master"  # Release only triggered on the master branch
  script:
    - echo "Creating a release..."
    # Add commands to create the release here
    # Example commands to create a release:
    # - git tag -a $CI_COMMIT_SHORT_SHA -m "Release $CI_COMMIT_SHORT_SHA"
    # - git push origin $CI_COMMIT_SHORT_SHA
