stages:
  - setup-database
  - unit-test

variables:
  MYSQL_DATABASE: "GestionUserVersMicro"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: "root"
  MYSQL_PASSWORD: ""
  IMAGE_MAVEN: maven:3.8.3

setup-database:
  image: mysql:8.0
  stage: setup-database
  services:
    - name: mysql:8.0
      alias: mysql
  script:
    - echo "Creating database schema and tables..."
    - mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
    # Add commands to populate the database if needed

unit-test:
  image: $IMAGE_MAVEN
  stage: unit-test
  services:
    - name: mysql:8.0
      alias: mysql
  script:
    - echo "Running unit tests..."
    # Assuming your tests use Maven to run and require the MySQL database
    - mvn test -Dspring.datasource.url=jdbc:mysql://mysql:3306/$MYSQL_DATABASE -Dspring.datasource.username=$MYSQL_USER -Dspring.datasource.password=$MYSQL_PASSWORD
