stages:
  - setup
  - test
  - release

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_MAVEN: maven:3.8.3

setup:
  image: mysql:8.0
  stage: setup
  script:
    - echo "Creating database schema and tables..."
    - mysql -h mysql-server -u root -proot_password -e "CREATE DATABASE IF NOT EXISTS your_database_name;"
    - mysql -h mysql-server -u root -proot_password your_database_name < path/to/your/database/schema.sql
  variables:
    MYSQL_DATABASE: "your_database_name"
    MYSQL_ROOT_PASSWORD: "root_password"
  services:
    - name: mysql:8.0
      alias: mysql-server

unit-test:
  image: $IMAGE_MAVEN
  stage: test
  script:
    - echo "Running unit tests..."
    - mvn test -Dspring.profiles.active=test
  services:
    - name: mysql:8.0
      alias: mysql-server
  variables:
    MYSQL_DATABASE: "your_database_name"
    MYSQL_ROOT_PASSWORD: "root_password"

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - echo "Creating a release..."
    # Add commands to create the release here
    # Example commands to create a release:
    # - git tag -a $CI_COMMIT_SHORT_SHA -m "Release $CI_COMMIT_SHORT_SHA"
    # - git push origin $CI_COMMIT_SHORT_SHA
