stages:
  - clean
  - build
  - static-code-analysis
  - setup-database
  - unit-test
  - coverage-test
  - release
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  IMAGE_MAVEN: maven:3.8.3
  MYSQL_DATABASE: GestionUserVersMicro
  MYSQL_ROOT_PASSWORD: root

clean:
  image: $IMAGE_MAVEN
  stage: clean
  script:
    - echo "Cleaning leftovers from previous builds"
    - mvn clean

build:
  image: $IMAGE_MAVEN
  stage: build
  script:
    - echo "Compiling the code..."
    - mvn install -B -DskipTests
  artifacts:
    paths:
      - target/

static-code-analysis:
  image: $IMAGE_MAVEN
  stage: static-code-analysis
  script:
    - echo "Running Static Code Analysis..."
    - echo "Checking duplicated code..."
    - mvn pmd:cpd-check
    - echo "Checking code standard..."
    - mvn pmd:pmd
setup-database:
  stage: setup-database
  
  services:
    - mysql
  image: mysql
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
unit-test:
  image: $IMAGE_MAVEN
  stage: unit-test
  script:
    - echo "Running database migrations..."
    - mvn flyway:migrate -Dspring.profiles.active=test  # Example: Use Flyway for DB migrations
    - echo "Running unit tests..."
    - mvn test -Dspring.profiles.active=test
 
coverage-test:
  image: $IMAGE_MAVEN
  stage: coverage-test
  needs:
    - job: unit-test
  script:
    - echo "Running coverage tests..."

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - echo "Creating a release..."
    # Add commands to create the release here
    # Example commands to create a release:
    # - git tag -a $CI_COMMIT_SHORT_SHA -m "Release $CI_COMMIT_SHORT_SHA"
    # - git push origin $CI_COMMIT_SHORT_SHA

