image: maven:3.8.3

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean install -B -DskipTests

test:
  stage: test
  script:
    - mvn test jacoco:report -Djacoco.destFile=custom/path/for/report/jacoco.exec
  artifacts:
    paths:
      - custom/path/for/report/  # Path to your custom Jacoco report directory
