services:
- mysql

variables:
  MYSQL_DATABASE: GestionUserVersMicro
  MYSQL_ROOT_PASSWORD: root

connect:
  image: mysql
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

